/* Run: NODE_PATH=<directory containing playwright> node tests/test_layout_browser.cjs */
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const { pathToFileURL } = require('node:url');
const root = path.resolve(__dirname, '..');
const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'espresense-layout-test-'));
const python = process.env.PYTHON || 'python3';
const screenshot = process.env.LAYOUT_SCREENSHOT || path.join(temp, 'layout-desktop.png');
let browser;
(async () => {
  const source = path.join(temp, 'geometry.yaml');
  // A synthetic 1px PNG exercises embedding without using anyone's house image.
  fs.writeFileSync(path.join(temp, 'plan.png'), Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jZAAAAABJRU5ErkJggg==', 'base64'));
  const original = fs.readFileSync(path.join(root, 'examples/geometry.example.yaml'), 'utf8');
  fs.writeFileSync(source, original.replace('    local: {w: 10, h: 8}', '    image: {file: plan.png, px_per_m: 1, origin_px: [0, 1]}\n    local: {w: 10, h: 8}') + '\nnotes: "Keep this metadata exactly"\n');
  const html = path.join(temp, 'editor.html');
  execFileSync(python, ['tooling/layout/build_layout_page.py', source, '--out', html], {cwd: root});
  browser = await chromium.launch({headless: true});
  const context = await browser.newContext({viewport: {width: 1440, height: 1200}, acceptDownloads: true});
  const page = await context.newPage(), errors = [], network = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', req => { if (/^https?:/.test(req.url())) network.push(req.url()); });
  await page.goto(pathToFileURL(html).href);
  assert.equal(await page.locator('.node').count(), 3);
  assert.equal(await page.locator('image').count(), 1);
  assert.match(await page.locator('image').getAttribute('href'), /^data:image\/png;base64,/);
  const parse = text => page.evaluate(input => jsyaml.load(input), text);
  const config = async () => parse(await page.locator('#yaml').inputValue());
  const download = async button => {
    const event = page.waitForEvent('download'); await page.locator(button).click();
    const file = await event, location = await file.path(); return fs.readFileSync(location, 'utf8');
  };
  assert.deepEqual((await config()).nodes[0].point, [1, 1, .5]);
  const floor = page.locator('#floor-0'), dot = floor.locator('[data-node="entry"]');
  const target = await dot.boundingBox();
  assert.equal(await page.evaluate(({x, y}) => document.elementFromPoint(x, y)?.dataset.node, {x: target.x + target.width / 2 + 18, y: target.y + target.height / 2}), 'entry');
  await dot.focus(); await page.keyboard.press('ArrowRight'); await page.keyboard.press('Shift+ArrowUp');
  assert.deepEqual((await config()).nodes[0].point, [1.05, 1.25, .5]);
  const localBefore = await dot.evaluate(el => [el.getAttribute('cx'), el.getAttribute('cy')]);
  await floor.getByLabel('Flip horizontal', {exact: true}).check();
  assert.deepEqual((await config()).nodes[0].point, [8.95, 1.25, .5]);
  assert.deepEqual(await dot.evaluate(el => [el.getAttribute('cx'), el.getAttribute('cy')]), localBefore);
  assert.equal(await floor.locator('image').evaluate(el => el.parentNode === document.querySelector('#floor-0 .node').parentNode), true);
  await floor.getByLabel('Flip vertical', {exact: true}).check();
  await floor.getByLabel('Offset X', {exact: true}).fill('2'); await floor.getByLabel('Offset X', {exact: true}).press('Tab');
  await floor.getByLabel('Offset Y', {exact: true}).fill('-1'); await floor.getByLabel('Offset Y', {exact: true}).press('Tab');
  assert.deepEqual((await config()).nodes[0].point, [10.95, 5.75, .5]);
  await dot.focus(); await page.keyboard.press('ArrowRight');
  assert.deepEqual((await config()).nodes[0].point, [11, 5.75, .5]);
  await floor.getByLabel('Height above floor', {exact: true}).fill('1.7'); await floor.getByLabel('Height above floor', {exact: true}).press('Tab');
  assert.equal((await config()).nodes[0].point[2], 1.7);
  // Pointer drag under two flips: screen-right must increase house X, not local X.
  const box = await dot.boundingBox(), beforeDrag = (await config()).nodes[0].point;
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
  await page.mouse.down(); await page.mouse.move(box.x + box.width / 2 + 35, box.y + box.height / 2 - 20, {steps: 5}); await page.mouse.up();
  const afterDrag = (await config()).nodes[0].point;
  assert.ok(afterDrag[0] > beforeDrag[0] && afterDrag[1] > beforeDrag[1]);
  await page.locator('#persist').check();
  const draft = await config(); await page.reload(); assert.deepEqual(await config(), draft);
  assert.equal(await page.locator('#persist').isChecked(), true);
  const upperOffset = page.locator('#floor-1').getByLabel('Offset X', {exact: true});
  await upperOffset.fill('12'); await upperOffset.press('Tab');
  assert.equal((await config()).floors[1].bounds[1][0], 18);
  const editedText = await download('#geometry'), edited = await parse(editedText);
  assert.equal(edited.notes, 'Keep this metadata exactly');
  assert.deepEqual(edited.floors[0].image, {file: 'plan.png', px_per_m: 1, origin_px: [0, 1]});
  assert.deepEqual(await parse(await download('#companion')), await config());
  const editedPath = path.join(temp, 'edited.yaml'); fs.writeFileSync(editedPath, editedText);
  execFileSync(python, ['tooling/layout/emit_companion.py', editedPath, '--out', path.join(temp, 'companion.yaml')], {cwd: root});
  assert.deepEqual(await parse(fs.readFileSync(path.join(temp, 'companion.yaml'), 'utf8')), await config());
  // Re-import is a lossless geometry roundtrip. An image filename cannot authorize backdrop reuse.
  await page.locator('#import').setInputFiles(editedPath);
  await page.waitForFunction(() => document.querySelector('#status').textContent.includes('Imported'));
  assert.deepEqual(await parse(await download('#geometry')), edited);
  assert.equal(await page.locator('image').count(), 0);
  assert.match(await floor.textContent(), /Plan image not loaded/);
  const beforeInvalid = await config();
  const bad = path.join(temp, 'bad.yaml'); fs.writeFileSync(bad, 'bounds: wrong\nfloors: []');
  await page.locator('#import').setInputFiles(bad);
  await page.waitForFunction(() => document.querySelector('#status').textContent.includes('Import failed'));
  assert.deepEqual(await config(), beforeInvalid);
  // A second source never inherits the first source's saved draft.
  const second = path.join(temp, 'second.yaml'), secondHtml = path.join(temp, 'second.html');
  fs.writeFileSync(second, original.replace('entry: [1, 1, 0.5]', 'entry: [2, 2, 0.5]'));
  execFileSync(python, ['tooling/layout/build_layout_page.py', second, '--out', secondHtml], {cwd: root});
  await page.goto(pathToFileURL(secondHtml).href);
  assert.deepEqual((await config()).nodes[0].point, [2, 2, .5]);
  assert.equal(await page.locator('#persist').isChecked(), false);
  await page.screenshot({path: screenshot, fullPage: true});
  await page.setViewportSize({width: 390, height: 844});
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.locator('#floor-0 [data-node="entry"]').scrollIntoViewIfNeeded();
  const mobileTarget = await page.locator('#floor-0 [data-node="entry"]').boundingBox();
  assert.equal(await page.evaluate(({x, y}) => document.elementFromPoint(x, y)?.dataset.node, {x: mobileTarget.x + mobileTarget.width / 2 + 18, y: mobileTarget.y + mobileTarget.height / 2}), 'entry');
  await page.screenshot({path: path.join(path.dirname(screenshot), 'layout-mobile.png'), fullPage: true});
  assert.deepEqual(errors, []); assert.deepEqual(network, []);
  console.log('PASS: offline image, keyboard/drag, flips/offsets, height, draft reload/isolation, YAML imports/exports, Python parity, desktop/mobile.');
  console.log('Screenshot: ' + screenshot);
})().catch(error => { console.error(error); process.exitCode = 1; }).finally(async () => { if (browser) await browser.close(); });
